package com.ytb.shopping.dao;

import com.ytb.shopping.pojo.Category;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_category
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_category
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_category
     *
     * @mbggenerated
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);

    /**
     * 获取品类子节点（平级）
     */
    List<Category> findChildCategory(int categoryId);

    /**
     * 修改品类名字
     */
    int setCategoryName(@Param("categoryId") Integer categoryId,@Param("categoryName") String categoryName);



}